name: Update SAM CLI with latest commit hash from APP Templates

on:
  push:
    branches:
      - main

jobs:
  updateCommitHash:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout SAM CLI
        uses: actions/checkout@v2
        with:
          repository: mndeveci/mock-cli
          ref: develop

      - name: Update Commit HASH
        run: cat <<< $(jq --arg commit_hash "$GITHUB_SHA" --indent 4 '.app_template_repo_commit =  $commit_hash' samcli/runtime_config.json) > samcli/runtime_config.json
      
      - name: Raise PR for SAM CLI
        uses: peter-evans/create-pull-request@v3
        with: 
          branch: "app_templates_hash_${{ env.GITHUB_SHA }}"
          base: develop
          title: "feat: update SAM CLI with latest App Templates HASH (${{ env.GITHUB_SHA }})"
          committer: ${{env.GIT_COMMIT_AUTHOR_NAME}} <${{env.GIT_COMMIT_AUTHOR_EMAIL}}>
          author: ${{env.GIT_COMMIT_AUTHOR_NAME}} <${{env.GIT_COMMIT_AUTHOR_EMAIL}}>
          body:
            This PR & commit is automatically created by GH action in App Templates repo to update the SAM CLI with latest hash of the App Templates.
          delete-branch: true
      