name: Update SAM CLI with latest commit hash from APP Templates

on:
  push:
    branches:
      - main

jobs:
  updateCommitHash:
    runs-on: ubuntu-latest
    steps:
      
      # - name: Run GH Action on SAM CLI
      #   uses: peter-evans/repository-dispatch@v2
      #   with: 
      #     token: ${{ secrets.PAT_TOKEN }}
      #     repository: mndeveci/mock-cli
      #     event-type: update-app-templates-hash
      - name: Test pushing commit
        run: |
          echo "Hello world!"

    
      